import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <body
        className={cn(
          'relative h-full font-sans antialiased text-gray-800',
          inter.className
        )}
      >
        {children}
        <Toaster
          position="top-center"
          richColors
        />
      </body>
    </html>
  )
}
